# Generated by Django 5.0.2 on 2026-08-12 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_coupon_transaction_refund_invoice_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price_monthly',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subscriptionusage',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='analytics',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='company_branding',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='featured_jobs',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_yearly',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='priority_support',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionusage',
            name='featured_jobs_used',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='job_post_limit',
            field=models.IntegerField(default=0, help_text='0 for Unlimited'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='resume_download_limit',
            field=models.IntegerField(default=0, help_text='0 for Unlimited'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
