# Generated by Django 5.0.2 on 2026-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_feature_jobs',
            field=models.BooleanField(default=False, help_text='Allow employer jobs to be automatically marked as Featured'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='company_branding',
            field=models.BooleanField(default=False, help_text='Highlight employer company profile'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
    ]
