# Generated by Django 5.0.2 on 2026-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=100, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/og_images/')),
                ('is_indexable', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='SmartJobs Team', max_length=100)),
                ('category', models.CharField(choices=[('career_tips', 'Career Tips'), ('news', 'News & Updates'), ('interview_prep', 'Interview Preparation'), ('industry_trends', 'Industry Trends')], default='career_tips', max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('billing', 'Billing & Payments'), ('general', 'General')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering position')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=100, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/og_images/')),
                ('is_indexable', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_or_company', models.CharField(help_text='e.g. Software Engineer at TCS', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
