# Generated by Django 5.0.2 on 2026-08-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_location', models.CharField(blank=True, help_text='e.g. Mumbai, Bangalore', max_length=255, null=True)),
                ('target_industry', models.CharField(blank=True, help_text='e.g. IT, Healthcare', max_length=255, null=True)),
                ('target_skills', models.CharField(blank=True, help_text='Comma-separated: Python, React', max_length=255, null=True)),
                ('target_exp_min', models.PositiveIntegerField(default=0, help_text='Min Experience in years')),
                ('target_exp_max', models.PositiveIntegerField(default=30, help_text='Max Experience in years')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('homepage', 'Homepage Ad'), ('search', 'Search Page Ad'), ('category', 'Category Ad'), ('sidebar', 'Sidebar Ad'), ('mobile', 'Mobile Ad'), ('sponsored_job', 'Sponsored Job'), ('featured_company', 'Featured Company'), ('sponsored_recruiter', 'Sponsored Recruiter')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='ads/banners/')),
                ('destination_url', models.URLField(help_text='Landing URL when user clicks ad')),
                ('is_active', models.BooleanField(default=True)),
                ('sponsored_job_id', models.IntegerField(blank=True, help_text='Job ID if Sponsored Job', null=True)),
                ('featured_company_id', models.IntegerField(blank=True, help_text='Company ID if Featured Company', null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=5.0, help_text='Cost Per Click (₹)', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adcampaign')),
            ],
        ),
    ]
