# Generated by Django 5.0.2 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
