# Generated by Django 5.2.17 on 2026-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_jobseekerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
